baseurl = "https://microcosmoz.github.io"
title = "micro cosmic-box"
copyright = "Copyright (c) 2008 - 2014, all rights reserved."
languageCode = "ja-jp"
canonifyurls = true
paginate = 3
theme = "hugo-dusk"
hasCJKLanguage = true # 記事のサマリー機能を有効にする。trueにしないと記事サマリーの文章量が大きくなりすぎる。

googleAnalytics = ""
disqusShortname = ""

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "vim" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/post/00/about/"
  weight = -100
  # pre = "<i class='fa fa-info-circle'></i>"

[author]
  name = "mikrocosmoz"

[params.meta]
  keywords = ""
  description = "Personal blog."

[params]
  email = "myemail"
  github = "microcosmoz"
  #gitlab = "gitlab id"
  twitter = "mikrocosmoz"
  #linkedin = "linkedin id"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#AFEEEE"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
